- .gitignore
- .travis.yml
- tests/README.md
- tests/functional/README.md
- tests/unit/.pytest_cache/v/cache/nodeids
- tests/unit/README.md
- tests/unit/sample_class_test.py
- tests/unit/sample_sysexit_test.py
- tests/unit/sample_test.py
closes #44 
- Set up travis integration and added `.travis.yml` config file, see build history (on master) [here](https://travis-ci.org/space-concordia-robotics)
- Added folder structure for unit + functional tests
- Pytest related updates to `.gitignore`
> Travis ci pytest setup 44

- requirements.txt
- robot/demos/RosArduinoBlinkLed/README.md
- robot/demos/RosArduinoBlinkLed/RosArduinoBlinkLed.ino
- robot/demos/RosArduinoBlinkLed/blinkLED.py
closes #59 
A simple proof of concept for using ROS topics (to toggle the builtin LED of an Arduino):
- Python publisher node
- Arduino subscriber node
- Topic: "toggle_led"
> Ros arduino blink led 59

- robot/basestation/static/js/app.js
- robot/basestation/static/js/arm.js
- robot/basestation/static/js/roslibjs/ros-helpers.js
- robot/basestation/static/js/rover.js
- robot/basestation/static/js/science.js
- robot/basestation/templates/RoverMotorControls.html
- robot/rospackages/src/mcu_control/scripts/RoverNode.py
- robot/rospackages/src/mux_selector/scripts/mux_select_server.py
- robot/rospackages/src/task_handler/scripts/Listener.py
- robot/rospackages/src/task_handler/scripts/start_ros_stream.sh
- robot/rover/config/my-webcams.rules
- robot/rover/config/rc.local
Closes #118 
Added new backup of odroid image [here](https://drive.google.com/drive/u/1/folders/12PI-sH2UVobUI4k0Et0AxUC4BJWMFUDr)
> Usb hub integration 118

- robot/basestation/static/js/app.js
- robot/basestation/static/js/arm.js
- robot/basestation/static/js/roslibjs/ros-helpers.js
- robot/basestation/static/js/rover.js
- robot/basestation/static/js/science.js
- robot/basestation/static/js/themes.js
The only drawback I have found is that this standard formatter removes the parentheses we have added for boolean conditions in ternary statements. :eyes:
Closes #159
> [#159] Run standard formatter

- robot/basestation/static/css/app.css
- robot/basestation/static/js/app.js
- robot/basestation/templates/ExtraControls.html
- robot/rospackages/README.md
- robot/rospackages/src/task_handler/scripts/start_ros_stream.sh
- robot/rover/config/my-webcams.rules
Added some extra nice to have features from @KoaTheKoala 's simultaneous-streams branch
Closes #168 
Closes #120
> Flip camera stream btn 168

- .style.yapf
- CONTRIBUTING.md
For a formatted view : https://github.com/space-concordia-robotics/robotics-prototype/blob/guidelines-178/CONTRIBUTING.md
> Programming Guidelines

- README.md
> [#220] Clarify README and fix cv_camera issues

- README.md
> [#241] Update README.md

- PULL_REQUEST_TEMPLATE.md
- pull_request_template.md
The file modified is the content that will be automatically pasted in this box after the merger of this PR closing #181
> [#181] Add PR template

- robot/rospackages/src/mux_selector/scripts/mux_select_server.py
- robot/util/rosRoverStart/rosRoverStartLocal.launch
closes #212 
Modify mux_selector_server.py to process correct number of args.
Add rosRoverStartLocal.launch which launches mux which arg "local".
> [#212] Update mux_selector_server.py and add rosRoverStartLocal.launch

- .gitignore
- robot/rover/README.md
- robot/util/emailer/README.md
- robot/util/emailer/emailIPAddress.js
- robot/util/emailer/package-lock.json
- robot/util/emailer/package.json
See PR name / issue description
closes #254 
Approval from at least one software team lead is necessary before merging.
---
> Add ability to set emailer recipients by an external text file

- robot/basestation/static/css/arm.css
- robot/basestation/templates/elements/controls/ManualControls.html
Redesigned manual controls for the arm. 
- Separated the table in three rows to make the buttons look more like the actual keyboard layout.
- Added the letters to the buttons
- Claws and arm controls are now separate blocks of buttons
closes #233
> Redesign controls 233

- requirements.txt
The joystick node doesnt work if you dont have pygame which isnt in the requirements.
- Added pygame as a library
closes #309 
> [#309] Add pygame as dependency

- robot/rover/Arm/Arm.ino
When commands are sent to the arm mcu to move a joint out of bounds, the mcu will now respond with the angle limits, thereby alerting the operator what range they're allowed to be in.
This test will not involve the rover because it can be tricky to get it into a configuration in which the angles are out of bounds, unless I (Josh) am present. We could do that together once you've tested it locally though.
1) Take a spare teensy 3.6 and upload Arm.ino onto it.
2) Open up the Arduino serial console
3) Send a command which is out of bounds to the teensy, such as "motor 2 angle 400"
4) Expected response is an error message which alerts you of the angle limits for that particular joint. Motors 1 and 5 may not have any angle limits. In that case an error message will never be generated.
closes …
> [#316] Add more descriptive error message

- robot/basestation/static/js/elements/feed/navbar.js
- robot/basestation/static/js/elements/tools/utils.js
Made default settings for the device channel and serial type. There are unique default settings for each page.
closes #325
> Change default channel 325

- robot/basestation/static/js/elements/feed/navbar.js
- robot/basestation/static/js/pages/arm.js
- robot/basestation/static/js/roslibjs/ros-helpers.js
The arm was constantly stuttering after playing it with for a while. The fix was to remove the spam from the log console, cluttering the page.
- Added minimum logging level. (See #202, where this feature should be expanded on)
- Put most of the spammy logs in debug level, which is not used by default
- Added some logs into logInfo and logDebug,  
closes #321 
> [#321] Set the spammy logs to logDebug and add some logInfos

- .travis.yml
- robot/rover/science/science.ino
I changed the travis config so it runs cmake and builds it
Given that this PR is only travis config, you cannot test the PR through conventional methods of clicking stuff in our GUI
1. Take a look at this link : https://travis-ci.org/github/space-concordia-robotics/robotics-prototype
2. You will find instances where Travis builds and when it doesnt. 
3. Observe that everything is in order in the latest build for my branch
closes #380 
> The Epic Quest to compile C++ with Travis has been completed.

- install_ros_kinetic.sh
Add the 2 aliases
Fix some potential errors
1. Copy paste this into an executable file that you create (don't forget to set it as executable):
```
#!/bin/bash
sh -c "echo \"\n\n#------ POST ROS INSTALLATION ------\" >> testfile"
sh -c "echo \"alias eb='nano ~/testfile'\" >> testfile"
sh -c "echo \"alias sb='source ~/testfile'\" >> testfile"
sh -c "echo \"alias gs='git status'\" >> testfile"
sh -c "echo \"alias gp='git pull'\" >> testfile"
sh -c "echo \"\nalias cw='cd ~/Programming/robotics-prototype/robot/rospackages/'\" >> testfile"
sh -c "echo \"alias cm='cw && catkin_make'\" >> testfile"
sh -c "echo \"\nexport ROS_MASTER_URI=http://localhost:11311\" >> testfile"
sh -c "echo \"export ROS_HOSTNAME=localhost\" >> testfile"
```
**You might need to create the `testfile` for it to work**
2. …
> Add aliases to the install_ros_kinetic script 

- EnvironmentSetup.sh
- README.md
- install_arduino_teensyduino.sh
Added an install and setup script for arduino + teensyduino, based off the commands found in the travis config file. Some stuff had to be removed, some stuff had to be added.
- Install + setup script tested while testing for #392 
- README manual steps updated
- Included this script execution in `EnvironmentSetup.sh`
1. Go to your arduino IDE folder (usually named something like `arduino-1.8.12`), `rm -rf <arduino_folder>`
2. Go to the root of the repo, run `./install_arduino_teensyduino.sh`
3. After the script is done, verify that it worked by navigating to your home folder where the arduion IDE folder is, `cd arduino-1.8.12`, then run `./arduino`
4. Verify that you can see in `Tools -> Board` some options with "Teensy" in it
5. (optional) If you have a teensy, try uploading a sketch to …
> [#402] Add install script for arduino and teensyduino

- docker/README.md
- docker/docker-compose.yml
- docker/rosbridge/Dockerfile
- docker/rosbridge/videogroupworkaround.sh
This PR gets the stream (camera) working in docker. 
Note: Edits were made to the Dockerfile which means that the docker build process will take a significant amount of time (~2 hours) even if it was built previously.
1. Run the project with docker using docker-compose up --build or follow the README instructions in the docker directory if it's your first time.
2. Visit `http://localhost:5000`
3. `Stream Select` > `/dev/video0` (It might take a few seconds before you can see `/dev/video0` in the dropdown menu)
4. Click the power button. The stream should start. If it doesn't, wait a few seconds and then try selecting the `/dev/video0` stream again (without hitting the power button this time).
1. With the project running in docker, visit `http://localhost:8080`
2. Click on `image_raw` to …
> Docker camera 474

- commit_message_hook.py
Exactly what the title says
Use copy git hook and test by committing dummy file.
closes #486 
> [#486] Remove useless imports from git commit hook

- robot/rover/internal_comms/src/CommandCenter.cpp
Use `free` to delete messages after they are sent
closes #527
> Potential fix for memory leak 527

- .github/workflows/build.yml
- .github/workflows/environment.sh
- .github/workflows/ros.sh
- .github/workflows/teensyduino.sh
Made the workflow execute on pushes to any branch.
Also made it checkout relevant branch since (i think) it used to pull master all the time.
Read logs I guess...
closes #526 
> Make Github actions run on relevant branch on branch push

- robot/rospackages/src/mcu_control/scripts/CommsNode.py
- robot/rospackages/src/mcu_control/scripts/ScienceCommands.py
- robot/rover/internal_comms/src/CommandCenter.cpp
- robot/rover/science/include/SciencePinSetup.h
- robot/rover/science/raman.ino
- robot/rover/science/src/Laser.cpp
- robot/rover/science/src/commands/ScienceCommandCenter.cpp
Added lines necessary for receiving commands for the laser.
> Laser comms

- .github/workflows/build.yml
- .github/workflows/environment.sh
- EnvironmentSetup.sh
- commit_message_hook.py
- scripts/arduino_install.sh
- scripts/ros_install.sh
Update ROS 2 installation script to verify and install ROS Humble and change CI to use old Arduino script
> Update ci to use ros2 for building instead of ros 601

- CMakeLists.txt
- robot/rospackages/src/arm_control_msg/CMakeLists.txt
- robot/rospackages/src/arm_control_msg/msg/ArmAxes.msg
- robot/rospackages/src/arm_control_msg/msg/ArmEndpoints.msg
- robot/rospackages/src/arm_control_msg/msg/ArmValues.msg
- robot/rospackages/src/arm_control_msg/msg/Wheels.msg
- robot/rospackages/src/arm_control_msg/package.xml
Added Msg types for Arm axes, Arm Endpoints, Arm values and wheels in arm-control-msg.
1. cd into robotics-prototype/robot
2. Run colcon build --packages-select arm_control_msg
closes #632 
> Create arm_control_msg directory for arm control msg types
