robot/basestation/README.md, robot/basestation/app.py, robot/basestation/templates/AsimovOperation.html, robot/rover/README.md, robot/rover/StreamDispatcher.py, robot/rover/start_stream.sh
closes #22 
A very simple implementation allowing us to view the arm camera stream, given that the `StreamDispatcher.py` process is running on the rover.
The methods/libraries may have to be changed since mjpeg streams aren't generally supported past the`img` tag and using the newer HTML `video` tag would give us more to work with.
This implementation does _not_ implement starting the stream or stopping it via commands sent from the base station, nor updating FPs. The stream must be initiated manually from the rover itself.
Tested on a single server/client ubuntu 16.04 machine.
=> View camera feed 22

PREPEND-README.md, commit-message-hook.sh, tests/functional/commit-prepender/prependertester.sh
Closes #67
Bash helper script to capture issue number from branch name and prepend it to commit message such as “[#<issue number>] ” using git hooks.
=> Number prepender 67

robot/rospackages/src/CMakeLists.txt, robot/rospackages/src/task_handler/scripts/Listener.py, robot/rospackages/src/task_handler/scripts/ScienceCommandListener.py, robot/rospackages/src/task_handler/scripts/start_stream.sh, robot/rospackages/src/task_handler/scripts/task_handler_client.py, robot/rospackages/src/task_handler/scripts/task_handler_server.py, robot/rospackages/src/task_handler/srv/HandleTask.srv, robot/rover/gpio/README.md, robot/rover/gpio/my-webcams.rules
All backend changes here, no frontend updates.
As long as we keep the usb ports for specific cameras, the changes in this PR will allow us to activate multiple different camera streams one at a time. No two streams can be on at the same time.
Additional upgrades were made to the task_handler ros service, as well as the Listener class to achieve this.
Now we can pass args as a third argument in the client calls, as well as query the running status of any task. Extra protection against running multiple "listener" type tasks was added for safety reasons, since we suspect that having multiple listeners opening the same serial port would mess things up for `pyserial`.
Still need to add UI changes but waiting to merge @vashmata 's branch regarding issue #99 first
=> Multiple cameras 101

.travis.yml
Closes #183 
For some reasons unknown, the check marks underneath our commits have disappeared. But when I sign into the travis site I can see the build history and now travis seems appeased.
We currently do not require those dependencies to run any unit tests or any other kind of tests. In the future, if we will need to, we could probably create a neutral user account just for this purpose so that travis can use it's credentials.
=> [#183] Bypass submodules

requirements.txt, robot/basestation/config/.bash_aliases
Closes #152 
I found the fix to run venv (python3+) with rosbridge_server, I simply had to install the missing python libraries, which in this case, only needed one. However I get this warning in the log `Failed to load Python extension for LZ4 support. LZ4 compression will not be available.`. I have not seen any effects of this warning, but I think we should definitely make sure everything is still functional considering that there's comp in like two weeks.
I'm assuming that it's the same issue for @vashmata @alihessami in your branch, some python packages probably just need to be put in `requirements.txt`
**Make sure you run `pip install -r requirements.txt`**
=> Allow venv to work with rosbridge_server

robot/basestation/config/.bash_aliases
This is because there is an issue with `venv` activated while launching rosbridge
=> Readd venv deactivation protection

robot/basestation/static/js/roslibjs/ros-helpers.js
hi it me
Created js functions for logging to mimic rospy functions: logInfo, logWarn, logErr, logFatal
These all call rosLog which is assisted by rosTimeStamp and publishRosLog. A new publisher was created so that these functions all log to /rosout. In practice this means you'll find the logs in rosout.log on the computer which is running as ROS MASTER. The functions include the timestamp and the log level.
I've left some todos. Most of them are bonus features that aren't necessarily required. However one missing aspect is the logic for activating/deactivating logDebug as this would need some discussion on where we put the variable that handles this.
- run the GUI with `rosgui` and `startgui`
- open a terminal and subscribe to `/rosout`: `rostopic echo /rosout`
- open the chrome console …
=> Roslibjs logging 211

EnvironmentSetup.sh, README.md, install_ros_kinetic.sh
Fixes a serious ROS/Catkin configuration error caused by the third-party ROS install script `install_ros_kinetic.sh`. 
The fix involves removing the erroneous addition of some commands to the `.bash_rc` and also removing the catkin workspace setup since we have our own process. 
- Removed bad sourcing
- Fixed catkin workspace setup
1. Either setup a fresh VM or create a new user account in Ubuntu
2. Run the setup script: `./EnvironmentSetup.sh`
3. Check if the GUI works: `rosgui` in one terminal followed by `startgui` in another, visit `localhost:5000` in chrome.
closes #359
For …
=> Fix environment setup 359

commit_message_hook.py, robot/util/utils.py
Git commit message hook now checks for cherry-pick file that is present in '.git' folder during cherry picking. In order to avoid duplicating the issue number in the commit message. 
1. Run `cp commit_message_hook.py .git/hooks/prepare-commit-msg` on 'fix-issue-tag-duplication-390' to cherry pick any older commit in branch, without pushing. (Use `git log` to view older commit hashes)
2. Use `git cherry-pick 613f09a` and run `git commit --allow-empty` to allow an empty commit. This still allows us to test if the hook will append the issue number to the message or not.
3. Check that the issue number wasn't duplicated in the commit message with `git commit --amend`.
4. Use `git reset HEAD^` to undo the commit. There shouldn't be any changes brought from the cherry pick if you used '613f09a', …
=> Fix issue tag duplication 390

.travis.yml, requirements.txt
Updates Twisted dependency to remove version alert.
Removes a dependency as twisted reinstalls it with the latest version anyways.
1. from root of repo, deactivate venv with `deactivate`
2. `rm -rf venv`
3. Use manual setup to:
a. create virtualenv: ```virtualenv -p `which python3.6` venv```
b. activate venv: `. venv/bin/activate`
b. install dependencies: `pip install -r requirements.txt -r requirements-dev.txt`
c. setup setuptools: `python setup.py develop`
4. confirm that gui runs: `rosgui`, `startgui`, visit `localhost:5000`
5. confirm that unit tests run: `pytest`
For Pull Requests that do not include code changes, it is not required to perform …
=> Fix Twisted alerts

install_ros_kinetic.sh, robot/basestation/config/.bash_aliases
I moved the customizable aliases to the install script so that they are included in ~/.bash_aliases upon installation.
I removed those aliases from their original location so they are not duplicated.
I remove dumb aliases b/c they are dumb... Add them to your own files if you actually use them.
1. Create an executable with this:
```
echo 'ROBOTICS_WS="/home/$USER/Programming/robotics-prototype"
BASE="$ROBOTICS_WS/robot/basestation"
ROVER="$ROBOTICS_WS/robot/rover"
ROSPACKAGES="$ROBOTICS_WS/robot/rospackages"
BASH_A="~/.bash_aliases"
NANORC="~/.nanorc"
alias ..="cd .."
alias b="cd -"
alias robotics="cd $ROBOTICS_WS"
alias base="cd $BASE"
alias rover="cd $ROVER"
alias arm="cd $ROVER/ArmDriverUnit"
alias wheels="cd $ROVER/MobilePlatform"
alias rostings="cd $ROSPACKAGES"
alias mcunode="cd …
```
=> Move aliases

robot/basestation/static/js/roslibjs/ros-helpers.js, robot/rospackages/src/mcu_control/scripts/PdsNode.py, robot/rospackages/src/mcu_control/scripts/SerialUtil.py
Minimal changes in order to get the PDS ros node working properly on startup, as well the corrections to the GUI so that it properly displays those PDS related values again.
Since this can really only be tested with the rover:
1. Start the rover
2. Start the GUI
3. All pages should show the battery voltage (slightly fluctuating), `N/A` for all the battery temp values, and on the rover page it should additionally fill the wheel motor table with electric current data.
closes #429
Aside from local testing and the General Integration Test it is implied that static analysis should be included in the verification process
=> Pds1 disconnect 429

robot/rospackages/src/mcu_control/scripts/SerialUtil.py
The ROS MCU nodes would always claim they found the microcontrollers. Even if it clearly should not have happened
FOR EACH in [Science, Rover, Arm], upload the code on a teensy.
For each node in [Science, Rover, Arm]. Launch the node, make sure that the MCU only identifies when there's the correct code
`rosrun mcunode $nodeNode.py`
End For
END FOR
Further, it should be verified with an Arduino that it also works with the PDS
closes #420
=> [#420] Fix identification issue

.gitignore
Add cmake files to gitignore
1. checkout branch
2. create a new branch based off this branch. Run cmake as per the wiki's instructions https://github.com/space-concordia-robotics/robotics-prototype/wiki/Building-the-C---code. 
3.Verify there's no unstaged cmake related files
closes #426 
=> [#426] Add cmake files to gitignore

robot/basestation/static/js/roslibjs/ros-helpers.js
Changes made to be able to display battery_temps values onto GUI. Previously, the values were never displayed and remained constantly as "NaN" as opposed to their published values. This fixes the bug where values were never properly displayed on the GUI.
1. Run `rosgui` and `startgui` in two terminal windows simultaneously.
2. Open the GUI on http://localhost:5000.
3. In terminal, publish a set of 3 battery temperatures using: `rostopic pub /battery_temps mcu_control/ThermistorTemps "therm1: <value1> therm2: <value2> therm3: <value3>"`
4. Observe the values displayed on the GUI.
Closes #433
=> [#433] Fix battery_temp ThermistorTemps values displayed on the GUI 

robot/rover/CMakeLists.txt, robot/rover/CMakeTemplate.txt.in, robot/rover/config/.bash_aliases, robot/rover/install_teensy_loader_cli.sh
Using CMake, upload the compiled C++ to a Teensy board, using the Teensy Loader CLI program from https://github.com/PaulStoffregen/teensy_loader_cli . It uploads one project at a time, although since the Rover uses 3 Teensys, this can easily be expanded to upload everything at once. Requires a Teensy board to test.
1. Ensure that `rover/config/.bash_aliases` is being sourced, preferably from `~/.bashrc`
2. Go to `robot/rover`, and run `./install_teensy_loader_cli.sh`
3. In `rover`, run `mkdir build && cd build`
4. `cmake ..`
5. `make`
6. Connect your Teensy3.6 board to your computer via usb
7. `upload science`
8. `upload Arm`
9. `upload MobilePlatform`
10. `cmake_clean`
closes #382
The approval from all software team leads is necessary before merging. 
Aside from local testing and the …
=> Cmake upload teensy 382

.dockerignore, docker/rosbridge/Dockerfile
This PR improves the rosbridge image build process so that Docker can use its cache as much as possible when installing dependencies and run only the compilation steps when files have been edited on the host.
1. Run the project with docker using `docker-compose up --build` or follow the README instructions in the docker directory if it's your first time.
2. `docker-compose down`
3. Make some arbitrary code changes in the `rover` or `rospackages` directory that can be easily seen.
4. `docker-compose up --build` again. The image building should take way less time. You should be able to tell from the build logs that Docker is only compiling source files.
5. Once everything is running again, you should be able to see whatever changes you've made reflected.
closes #475
The approval from all …
=> Docker build optimizations 475

robot/basestation/static/js/roslibjs/ros-helpers.js
Implement a check to replace the element with "N/A" if the temp is equal to 999.9
1. `rosgui` and `startgui`
2. Open gui
3. `rostopic pub /battery_temps <TAB>x9999`
4. Set any temps to 999.9
5. Check in GUI that temp is now `N/A` and no popup came up
6. (Optional) Set temp to 999 and check that popup screams at you
closes #317 
=> Set to N/A and stop front-end from yelling at you if temp is 999.9

.gitmodules, .travis.yml
Added autonomy-packages as submodule in catkin workspace in robotics-prototype
closes #489 
=> [#489] Add autonomy-packages as submodule

robot/rover/internal_comms/include/CommandCenter.h, robot/rover/internal_comms/src/CommandCenter.cpp
Fixes the issue of getting garbage when back to back `Serial.read()`s are performed. If you `Serial.read()` before it's "ready" you run the risk of reading garbage values.
Note: I tested using an Arduino Nano. I don't know what happens with a teensy. Also you need some code that links to and uses the internal comms library found in `robot/rover/internal_comms/`
1. In `robot/rover/internal_comms/src/CommandCenter.cpp` replace all instances of `waitForSerial()` with `Serial.read()`
2. Serial.print the two bytes inside `readArgSize()`
3. Compile and upload your program.
4. Run it, send in some bytes and you should see that you get corrupted values. In other words you don't get the same as the bytes you sent in.
5. Undo changes from 1
6. Run the experiment again. You should get the values you …
=> Make the Serial available check before every Serial.read()

robot/rospackages/src/mcu_control/scripts/ArmNode.py, robot/rover/Arm/Arm.ino, robot/rover/Arm/src/commands/ArmCommandCenter.cpp, robot/rover/comms_demo/arduino_demos/pong_bing/pong_bing.ino, robot/rover/internal_comms/include/CommandCenter.h, robot/rover/internal_comms/src/CommandCenter.cpp
This PR just builds on the previous one to better integrate the new comms with the arm code. We basically added a python node and a  .ino file to test sending/reading commands
1. Upload pong_bing.ino to an arduino
2. Uncomment the print statements in `ArmNode.py`
3. Run roscore + `python3  robot/rospackages/src/mcu_control/scripts/ArmNode.py`
4. You should see commands being printed out correctly. It includes an array of floats and a string.
=> Comms debug string

robot/rover/internal_comms/src/CommandCenter.cpp
The message object only has a reference to the contents but the contents may get cleared once the object was pushed to the message queue. To avoid problems, the contents are copied to a new address.
=> [#0] Copy contents to avoid bad pointer

robot/rover/Arm/include/DcMotor.h, robot/rover/MobilePlatform/src/DcMotor.cpp
Upgraded the motor pwm pin frequencies to 18kHz to greatly reduce the 2V dip in the power rail. 
Josh must confirm that it worked.
=> [#547] Make pwm pin frequencies 18kHz
